### PR TITLE
Upgrading to Play 2.4.1

### PR DESCRIPTION
**Pull request by manuelbernhardt**
Because what would the world be without JSON iteratees

- tested against Chapter 2 of my book
- not sure whether it should already be version 1.5.0

### CODE REVIEW

**Comment by jroper** [comment]
Thanks @manuelbernhardt!

**Comment by jroper** [comment]
Closing/reopening to trigger travis build.

**Comment by jroper** [comment]
1.5.0 is released, and should be hitting a maven central CDN node near you within 10 minutes.

**Comment by manuelbernhardt** [comment]
Thanks, great!

**Pull request merged**
