### PR TITLE
Upgrade to Play 2.5.3

### PR DESCRIPTION
**Pull request by martinstuder**
This pull request is to upgrade the library to Play 2.5.3. This is in preparation of a potential upgrade of the anormcypher project (https://github.com/AnormCypher/AnormCypher) to Play 2.5.3.

### CODE REVIEW

**Comment by martinstuder** [comment]
Here is the corresponding anormcypher pull request: https://github.com/AnormCypher/AnormCypher/pull/56

**Comment by jroper** [comment]
Play 2.5 dropped support for Scala 2.10, so this upgrade needs to change the build so it doesn't cross build against Scala 2.10 (that's why travis is failing).

**Comment by martinstuder** [comment]
Given that checks pass, is there a chance to get this merged? Would be great to see AnormCypher on Play 2.5.x.

**Comment by ICornwell** [comment]
Words can not express how happy this has made me. Rather new to Scala, couldn't work the Enumeratee.map bit out myself. Any news on whether this will get merged back? Is AnormCypher still current? Scala and Neo4j seem like a great match, but all the Neo4j clients seem old and neglected.

**Comment by jroper** [comment]
Sorry about taking so long to get to this. I've released 1.6.0 for Play 2.5.

**Pull request merged**
